version: '3.1'

services:

  db:
    container_name: ort_db
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ort


  api:
    container_name: ort_api
    image: riverfolk/ort-backend:latest
    restart: always
    environment: 
      PG_CONN: postgres://postgres:postgres@db:5432/ort?sslmode=disable
      METRIC_DELETE_DAYS: 120
      ROLLBAR_TOKEN: supersecret
      ORT_ENV: production

    ports:
      - 8080:80