version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ort_production


  ort:
    image: riverfolk/ort-backend
    restart: always
    ports:
      - 80:80