version: '3.1'

services:

  db:
    name: ort_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ort


  api:
    name: ort_api
    image: riverfolk/ort-backend:latest
    restart: always
    environment: 
      PG_CONN: postgres://postgres:postgres@db:5432/ort?sslmode=disable
    ports:
      - 80:80