version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ort


  ort:
    image: riverfolk/ort-backend:latest
    restart: always
    environment: 
      PG_CONN: postgres://postgres:postgres@127.0.0.1:5432/ort?sslmode=disable
    ports:
      - 80:80